### ISSUE TITLE
Transparently encode native BigInt as strings

### ISSUE THREAD

**Issue by zdm** [darrachequesne/notepack#24]
Hi,
Is it possible to add support to encode BigInt as strings trransparently?

Something like this:
```
case 'bigint': 
		return _encode(bytes, defers, value.toString());
```

If this is acceptable, I can create pull request.

**Comment by darrachequesne** [comment]
Hi!

That's a good question actually. I'm wondering whether we should: 

- encode it as string
- encode it as uint 64 (by using the [BigInt.asUintN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/asUintN) method)
- use an [extension type](https://github.com/msgpack/msgpack/blob/master/spec.md#extension-types)

What is your opinion in this?

That being said, you should be able to use the same trick as with `JSON.stringify()` ([here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Use_within_JSON)):

```js
BigInt.prototype.toJSON = function() { return this.toString()  }
```

**Comment by zdm** [comment]
BigInt.asUintN has limitations to the number of bits -  in some cases we can lost data.

I think better is to encode / decode using custom extension type. Send it as string, and decode to BigInt.

**Comment by zdm** [comment]
so, what do you think?

**Comment by darrachequesne** [comment]
Yes, I think the best way is to add support for custom extensions (also requested in https://github.com/darrachequesne/notepack/issues/18).

I won't have much time for that in the short term though, would you have time to implement it? I'll be happy to merge it :+1:

**Comment by zdm** [comment]
What extension type in hex can be taken for this?

**Comment by zdm** [comment]
I will take `0x01` for `BigInt`.

PR ready.
