### ISSUE TITLE
toJSON support

### ISSUE THREAD

**Issue by roeycohen** [darrachequesne/notepack#6]
Hi, 

It would be nice if you add support for toJSON function.
this way, the library will be more compatible with JSON.stringify.

what do you think?
i can create a pull request if you approve.

10x

**Comment by darrachequesne** [comment]
Let's do this :+1:

**Comment by roeycohen** [comment]
ok, i'll be back!

**Comment by darrachequesne** [comment]
Closed by https://github.com/darrachequesne/notepack/pull/8.
